version: "2"
run:
  go: '1.24'
linters:
  settings:
    gosec:
      excludes:
        - G115
    dupl:
      threshold: 100
    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 4
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
    gocyclo:
      min-complexity: 20
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    lll:
      line-length: 175
    misspell:
      locale: US
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: true # don't require nolint directives to be specific about which linter is being skipped
  default: "none"
  enable:
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - copyloopvar
    - gocyclo
    - funlen
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - gosmopolitan
    - misspell
    - nakedret
    - revive
    - unconvert
    - unused
    - whitespace
    - bodyclose
    - noctx
    - unparam
    - iface
    - sqlclosecheck
    - wastedassign
    - errchkjson
    - staticcheck
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/tunein/go-cache
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
